### PR TITLE
Use secrets instead of plain text env variables

### PR DESCRIPTION
**Pull request by halkeye**
I use helm-secrets to encode secrets then have it deployed via CI. Helm's output will encode secrets as ++, but regular env variables get the full string.

This PR moves all the generated env variables to secrets (anything in values from env: and envFrom: are kept as env). from testing locally it seems to work smoothly

### CODE REVIEW

**Comment by halkeye** [comment]
I can't tell in the new UI who watches this repo, so I'm going to ping @BeryJu, hopefully its not noise for you ❤️

**Comment by BeryJu** [comment]
It looks good from what I can tell, and CI passes, but I havent written the original logic, that was all @dirtycajunrice, so I'll see if I can get his opinion on it

**Comment by halkeye** [comment]
Gee thanks

This pr isn't useless or needless. It may not be the final destination but its moving in the right direction. Right now I can't commit any of my configuration because helm outputs diffs to the definitions as plain text. By using secrets helm will censor them.

Is pulling env from the definition vs secret the same thing in the end? Yes. But it's the start of the process that matters to me.

Once they are in secrets another future pr could be setup to read the secret. Via file. Via Kube API calls. Etc.

But what's in place right now doesn't work for and I'm providing a solution

**Comment by halkeye** [comment]
for example, changing the output with this patch looks like
```
$ helmfile diff
Adding repo authentik git+https://github.com/halkeye/goauthentik-helm@charts?ref=use-secrets
"authentik" has been added to your repositories

Decrypting secret /home/halkeye/go/src/github.com/halkeye/dohelmfile/namespaces/authentik/authentik-secrets.yaml
Decrypting /home/halkeye/go/src/github.com/halkeye/dohelmfile/namespaces/authentik/authentik-secrets.yaml

Comparing release=authentik, chart=authentik/authentik
authentik, authentik-secrets, Secret (v1) has changed:
  # Source: authentik/templates/secret.yml
  apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app.kubernetes.io/instance: authentik
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: authentik
      app.kubernetes.io/version: 2021.12.5
      helm.sh/chart: authentik-5.2.2
    name: authentik-secrets
  data:
    AUTHENTIK_AVATARS: 'REDACTED # (8 bytes)'
-   AUTHENTIK_EMAIL__FROM: '-------- # (17 bytes)'
+   AUTHENTIK_EMAIL__FROM: '++++++++ # (18 bytes)'
    AUTHENTIK_EMAIL__HOST: 'REDACTED # (30 bytes)'
    AUTHENTIK_EMAIL__PORT: 'REDACTED # (3 bytes)'
    AUTHENTIK_EMAIL__TIMEOUT: 'REDACTED # (2 bytes)'
    AUTHENTIK_EMAIL__USE_SSL: 'REDACTED # (5 bytes)'
    AUTHENTIK_EMAIL__USE_TLS: 'REDACTED # (5 bytes)'
    AUTHENTIK_ERROR_REPORTING__ENABLED: 'REDACTED # (4 bytes)'
    AUTHENTIK_ERROR_REPORTING__ENVIRONMENT: 'REDACTED # (3 bytes)'
    AUTHENTIK_ERROR_REPORTING__SEND_PII: 'REDACTED # (5 bytes)'
    AUTHENTIK_GEOIP: 'REDACTED # (25 bytes)'
    AUTHENTIK_LOG_LEVEL: 'REDACTED # (4 bytes)'
    AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE: 'REDACTED # (40 bytes)'
    AUTHENTIK_POSTGRESQL__HOST: 'REDACTED # (38 bytes)'
    AUTHENTIK_POSTGRESQL__NAME: 'REDACTED # (9 bytes)'
    AUTHENTIK_POSTGRESQL__PASSWORD: 'REDACTED # (27 bytes)'
    AUTHENTIK_POSTGRESQL__PORT: 'REDACTED # (4 bytes)'
    AUTHENTIK_POSTGRESQL__S3_BACKUP__INSECURE_SKIP_VERIFY: 'REDACTED # (5 bytes)'
    AUTHENTIK_POSTGRESQL__USER: 'REDACTED # (9 bytes)'
    AUTHENTIK_REDIS__HOST: 'REDACTED # (40 bytes)'
    AUTHENTIK_REDIS__PASSWORD: 'REDACTED # (32 bytes)'
    AUTHENTIK_SECRET_KEY: 'REDACTED # (36 bytes)'
    GEOIPUPDATE_ACCOUNT_ID: 'REDACTED # (6 bytes)'
    GEOIPUPDATE_LICENSE_KEY: 'REDACTED # (16 bytes)'
  type: Opaque
```

which means its safe to run in CI where people can see the output. Yes i'd love to see even more secret security, but this is still a win.

**Comment by halkeye** [comment]
its not really an argument. My solution was a step in the right direction, not the end goal. I went ahead and forked the helm chart (and updated the latest parent common chart).  Your more than welcome to use any of it, but I'm not going to fight for an unwanted feature 

https://github.com/halkeye/dok8s/tree/main/charts/authentik

**Pull request closed without merging**
