### PR TITLE
Adds configuration for automated install of authentik

### PR DESCRIPTION
**Pull request by simonkaiser9**
Adds configuration options for automated install of Authentik for helm installs.
Using the env configurations did not work out for me, as these were prefixed in the templates and I think it makes sense to have the options more prominently.

### CODE REVIEW

**Comment by simonkaiser9** [comment]
I saw the missing dependencies when testing locally as well and bumped the versions to more current charts. I did not feel competent to make the changes here as well as I cannot make sure, that the newer versions work without any regressions...

**Comment by BeryJu** [comment]
Hi, thanks for the PR! I reckon it'll probably be easier if we make the prefix of the bootstrap variables match the normal prefix rather than add extra logic

**Comment by simonkaiser9** [comment]
@BeryJu That makes even more sense, I was wondering why AK_ADMIN has a different prefix to begin with but did not think about making the correct change. I'll close this PR then. Thanks for the change!
Authentik is really great, thanks for the effort.

**Comment by BeryJu** [comment]
Yeah I initially added the options for testing and didn't really expect many people besides me to use them, so I never really thought about their usage with helm

**Pull request closed without merging**
