### PR TITLE
authentik: ci: rename values files to run with chart-testing correctly

### PR DESCRIPTION
**Pull request by wrenix**
current the chart-testing does not run with the value-files ...

https://github.com/helm/chart-testing/blob/main/doc/ct_lint.md

> Charts may have multiple custom values files matching the glob pattern **'*-values.yaml'** in a directory named 'ci' in the root of the chart's directory. The chart is linted for each of these files. If no custom values file is present, the chart is linted with defaults.

**'*-values.yaml'**

### CODE REVIEW

**Review by BeryJu — CHANGES_REQUESTED** [review]
I don't think we need to bump the version for this change

Aside from that it would be nice to have a better way to see failures, but I assume there's no way to integrate this with a GitHub Actions Matrix

**Comment by wrenix** [comment]
Why need an Github action matrix, if the `ct lint` does that job?

```
Linting chart with values file "charts/authentik/ci/ct-blueprints-values.yaml"...

>>> helm lint charts/authentik --values charts/authentik/ci/ct-blueprints-values.yaml
==> Linting charts/authentik

1 chart(s) linted, 0 chart(s) failed

Linting chart with values file "charts/authentik/ci/ct-geoip-values.yaml"...

>>> helm lint charts/authentik --values charts/authentik/ci/ct-geoip-values.yaml
==> Linting charts/authentik

1 chart(s) linted, 0 chart(s) failed

Linting chart with values file "charts/authentik/ci/ct-hpa-values.yaml"...

>>> helm lint charts/authentik --values charts/authentik/ci/ct-hpa-values.yaml
==> Linting charts/authentik

1 chart(s) linted, 0 chart(s) failed

Linting chart with values file "charts/authentik/ci/ct-pdb-max-values.yaml"...

>>> helm lint charts/authentik --values charts/authentik/ci/ct-pdb-max-values.yaml
==> Linting charts/authentik

1 chart(s) linted, 0 chart(s) failed

Linting chart with values file "charts/authentik/ci/ct-pdb-min-values.yaml"...

>>> helm lint charts/authentik --values charts/authentik/ci/ct-pdb-min-values.yaml
==> Linting charts/authentik

1 chart(s) linted, 0 chart(s) failed

Linting chart with values file "charts/authentik/ci/ct-values.yaml"...

>>> helm lint charts/authentik --values charts/authentik/ci/ct-values.yaml
==> Linting charts/authentik

1 chart(s) linted, 0 chart(s) failed

------------------------------------------------------------------------------------------------------------------------
 ✔︎ authentik => (version: "2024.2.3", path: "charts/authentik")
```

**Comment by wrenix** [comment]
remove Chart.yaml - version again

**Review by BeryJu — APPROVED** [review]

**Comment by rissson** [comment]
Let's fix the CI before merging though

**Comment by rissson** [comment]
Yeah it was just a general comment not directed at you. I'll take some time and fix the tests before merging.

**Pull request merged**
