### PR TITLE
Add tolerations to deployments

### PR DESCRIPTION
**Pull request by eugene-davis**

### CODE REVIEW

**Comment by BeryJu** [comment]
thanks for the PR, you'll have to bump the chart version for the pipeline to pass

**Comment by eugene-davis** [comment]
@BeryJu I bumped it to today's date, please let me know if  I should have just incremented.

**Comment by BeryJu** [comment]
It should be 7.3, please also check in the other markdown files (I should probably add a script to make a bump easier)

**Review by BeryJu — APPROVED** [review]

**Comment by eugene-davis** [comment]
Ok, I think I got all the chart versions bumped.

**Pull request merged**
